-- 自动生成：把当前离线看板的数据灌入 D1（tools/build_seed.py）
-- 执行: npx wrangler d1 execute roomsense-db --file=./seed.sql

DELETE FROM overrides;
DELETE FROM inventory;
DELETE FROM sku_master;

-- 1) 周销售趋势（人工矫正值，导入明细后可删）
INSERT INTO overrides(key, value, note) VALUES('weekly.W23', '46', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W24', '840', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W25', '1870', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W26', '1844', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W27', '2581', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W28', '3706', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W29', '2989', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W30', '2598', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W31', '4579', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W32', '2845', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W33', '5514', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W34', '3736', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('weekly.W35', '4737', '迁移自离线看板');

-- 2) SKU × 周 销量（人工矫正值）
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W23', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W24', '3', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W25', '4', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W26', '6', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W27', '4', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W28', '15', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W29', '9', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W30', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W31', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W32', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W33', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W34', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1169R.W35', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W23', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W24', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W25', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W26', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W27', '3', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W28', '4', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W29', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W30', '3', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W31', '4', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W32', '3', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W33', '8', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1167F.W34', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W23', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W24', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W25', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W26', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W27', '11', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W28', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W29', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W30', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W31', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W32', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W33', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.PL-1168R.W34', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W23', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W24', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W25', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W26', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W27', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W28', '5', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W29', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W30', '5', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W31', '3', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W32', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W33', '3', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-Q.W34', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W23', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W24', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W25', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W26', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W27', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W28', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W29', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W30', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W31', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W32', '3', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W33', '6', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-D.W34', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W23', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W24', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W25', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W26', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W27', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W28', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W29', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W30', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W31', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W32', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W33', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-KS.W34', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W23', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W24', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W25', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W26', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W27', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W28', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W29', '3', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W30', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W31', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W32', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W33', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1772-S.W34', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W23', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W24', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W25', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W26', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W27', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W28', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W29', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W30', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W31', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W32', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W33', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1666-Q.W34', '4', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W23', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W24', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W25', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W26', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W27', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W28', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W29', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W30', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W31', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W32', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W33', '3', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-K.W34', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W23', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W24', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W25', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W26', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W27', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W28', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W29', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W30', '1', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W31', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W32', '0', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W33', '2', '迁移自离线看板');
INSERT OR REPLACE INTO overrides(key, value, note) VALUES('skuWeek.MA-1667-D.W34', '0', '迁移自离线看板');

-- 3) 平台分布 / 品类分析（整体覆盖）
INSERT INTO overrides(key, value, note) VALUES('platData', '[{"name": "Bunnings", "thisWeek": 1515.65, "lastWeek": 0, "share": "37%"}, {"name": "Dropshipzone", "thisWeek": 1257.22, "lastWeek": 1138.63, "share": "31%"}, {"name": "Kmart", "thisWeek": 515.74, "lastWeek": 26.98, "share": "13%"}, {"name": "Amazon Marketplace", "thisWeek": 503.79, "lastWeek": 1563.02, "share": "12%"}, {"name": "Kogan", "thisWeek": 264.53, "lastWeek": 0, "share": "6%"}, {"name": "Temu - AU", "thisWeek": 41.78, "lastWeek": 0, "share": "1%"}, {"name": "Big W", "thisWeek": 0, "lastWeek": 834.03, "share": "0%"}, {"name": "Ebay", "thisWeek": 0, "lastWeek": 0, "share": "0%"}, {"name": "Everyday Rewards", "thisWeek": 0, "lastWeek": 0, "share": "0%"}, {"name": "Myer", "thisWeek": 0, "lastWeek": 0, "share": "0%"}, {"name": "Temu - US", "thisWeek": 0, "lastWeek": 120, "share": "0%"}, {"name": "Woolworths", "thisWeek": 0, "lastWeek": 154.5, "share": "0%"}]', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('catData', '[{"cat": "床垫类", "orders": 10, "units": 11, "revenue": 3651, "cumUnits": 104}, {"cat": "枕头类", "orders": 1, "units": 2, "revenue": 86, "cumUnits": 92}]', '迁移自离线看板');

-- 4) KPI
INSERT INTO overrides(key, value, note) VALUES('kpi.total', '37852.38', '用户确认口径');
INSERT INTO overrides(key, value, note) VALUES('kpi.thisWeek', '4737', '8/22-8/28 用户确认总额');
INSERT INTO overrides(key, value, note) VALUES('kpi.netJuly', '13843', '7月净结算额');
INSERT INTO overrides(key, value, note) VALUES('kpi.adsJuly', '1054', '7月广告投入');

-- 5) SKU 主数据（品类）
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1666-34-S', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1666-34-KS', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1666-34-D', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1666-34-Q', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1667-30-S', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1667-30-KS', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1667-30-D', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1667-30-Q', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1667-30-K', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-PL-1167F-WH', '枕头', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-PL-1168R-WH', '枕头', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-PL-1169R-WH', '枕头', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1772-26-S', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1772-26-KS', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1772-26-D', '床垫', 21);
INSERT OR REPLACE INTO sku_master(sku, category, safety_days) VALUES('XFKF-MA-1772-26-Q', '床垫', 21);

-- 6) 库存明细
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1666-34-S', 7, 10, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1666-34-KS', 12, 15, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1666-34-D', 7, 10, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1666-34-Q', 19, 34, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1667-30-S', 11, 15, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1667-30-KS', 13, 15, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1667-30-D', 19, 30, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1667-30-Q', 32, 39, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1667-30-K', 18, 25, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-PL-1167F-WH', 25, 53, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-PL-1168R-WH', 27, 48, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-PL-1169R-WH', 0, 43, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1772-26-S', 12, 20, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1772-26-KS', 22, 30, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1772-26-D', 2, 20, 0, '', datetime('now'));
INSERT OR REPLACE INTO inventory(sku, on_hand, inbound, safety_stock, eta, updated_at) VALUES('XFKF-MA-1772-26-Q', 44, 64, 0, '', datetime('now'));

-- 7) 库存表在无销售明细时（d7/可售天数算不出来），先沿用离线看板的结论
INSERT INTO overrides(key, value, note) VALUES('invData', '[{"sku": "XFKF-MA-1666-34-S", "type": "床垫", "inv": 7, "recv": 10, "d7": 0, "d30": 0.14, "days": null, "status": "tag-amber", "statusText": "偏低", "suggest": 10}, {"sku": "XFKF-MA-1666-34-KS", "type": "床垫", "inv": 12, "recv": 15, "d7": 0, "d30": 0.14, "days": null, "status": "tag-green", "statusText": "尚可", "suggest": 0}, {"sku": "XFKF-MA-1666-34-D", "type": "床垫", "inv": 7, "recv": 10, "d7": 0.14, "d30": 0.14, "days": 50, "status": "tag-amber", "statusText": "偏低", "suggest": 15}, {"sku": "XFKF-MA-1666-34-Q", "type": "床垫", "inv": 19, "recv": 34, "d7": 0.57, "d30": 0.57, "days": 33, "status": "tag-green", "statusText": "尚可", "suggest": 10}, {"sku": "XFKF-MA-1667-30-S", "type": "床垫", "inv": 11, "recv": 15, "d7": 0.14, "d30": 0.14, "days": 79, "status": "tag-green", "statusText": "尚可", "suggest": 0}, {"sku": "XFKF-MA-1667-30-KS", "type": "床垫", "inv": 13, "recv": 15, "d7": 0, "d30": 0.14, "days": null, "status": "tag-green", "statusText": "尚可", "suggest": 0}, {"sku": "XFKF-MA-1667-30-D", "type": "床垫", "inv": 19, "recv": 30, "d7": 0, "d30": 0.43, "days": null, "status": "tag-green", "statusText": "充足", "suggest": 0}, {"sku": "XFKF-MA-1667-30-Q", "type": "床垫", "inv": 32, "recv": 39, "d7": 0.29, "d30": 0.29, "days": 110, "status": "tag-green", "statusText": "充足", "suggest": 0}, {"sku": "XFKF-MA-1667-30-K", "type": "床垫", "inv": 18, "recv": 25, "d7": 0, "d30": 0.43, "days": null, "status": "tag-green", "statusText": "尚可", "suggest": 0}, {"sku": "XFKF-PL-1167F-WH", "type": "枕头", "inv": 25, "recv": 53, "d7": 0, "d30": 1.0, "days": null, "status": "tag-green", "statusText": "充足", "suggest": 0}, {"sku": "XFKF-PL-1168R-WH", "type": "枕头", "inv": 27, "recv": 48, "d7": 0.29, "d30": 0.86, "days": 93, "status": "tag-green", "statusText": "充足", "suggest": 0}, {"sku": "XFKF-PL-1169R-WH", "type": "枕头", "inv": 0, "recv": 43, "d7": 0, "d30": 0.71, "days": 0, "status": "tag-red", "statusText": "断货", "suggest": 150}, {"sku": "XFKF-MA-1772-26-S", "type": "床垫", "inv": 12, "recv": 20, "d7": 0, "d30": 0.14, "days": null, "status": "tag-green", "statusText": "尚可", "suggest": 10}, {"sku": "XFKF-MA-1772-26-KS", "type": "床垫", "inv": 22, "recv": 30, "d7": 0.14, "d30": 0.29, "days": 157, "status": "tag-green", "statusText": "充足", "suggest": 0}, {"sku": "XFKF-MA-1772-26-D", "type": "床垫", "inv": 2, "recv": 20, "d7": 0.14, "d30": 0.29, "days": 14, "status": "tag-red", "statusText": "紧急", "suggest": 30}, {"sku": "XFKF-MA-1772-26-Q", "type": "床垫", "inv": 44, "recv": 64, "d7": 0.14, "d30": 0.43, "days": 314, "status": "tag-green", "statusText": "充足", "suggest": 0}]', '迁移自离线看板');
INSERT INTO overrides(key, value, note) VALUES('invSuggestData', '[{"sku": "XFKF-PL-1169R-WH", "cat": "枕头", "inv": 0, "weekQty": 0, "d7": 0, "days": 0, "status": "断货", "suggest": 150, "priority": "P0"}, {"sku": "XFKF-MA-1772-26-D", "cat": "床垫", "inv": 2, "weekQty": null, "d7": null, "days": null, "status": "紧急", "suggest": 30, "priority": "P0"}, {"sku": "XFKF-MA-1666-34-D", "cat": "床垫", "inv": 7, "weekQty": null, "d7": null, "days": null, "status": "偏低", "suggest": 15, "priority": "P1"}, {"sku": "XFKF-MA-1666-34-S", "cat": "床垫", "inv": 7, "weekQty": null, "d7": null, "days": null, "status": "偏低", "suggest": 10, "priority": "P1"}, {"sku": "XFKF-MA-1772-26-S", "cat": "床垫", "inv": 12, "weekQty": null, "d7": null, "days": null, "status": "偏低", "suggest": 15, "priority": "P1"}, {"sku": "XFKF-PL-1168R-WH", "cat": "枕头", "inv": 27, "weekQty": null, "d7": null, "days": null, "status": "充足", "suggest": 0, "priority": "-"}, {"sku": "XFKF-PL-1167F-WH", "cat": "枕头", "inv": 25, "weekQty": null, "d7": null, "days": null, "status": "充足", "suggest": 0, "priority": "-"}, {"sku": "XFKF-MA-1667-30-KS", "cat": "床垫", "inv": 13, "weekQty": null, "d7": null, "days": null, "status": "尚可", "suggest": 0, "priority": "-"}, {"sku": "XFKF-MA-1666-34-Q", "cat": "床垫", "inv": 19, "weekQty": null, "d7": null, "days": null, "status": "尚可", "suggest": 0, "priority": "-"}, {"sku": "XFKF-MA-1667-30-K", "cat": "床垫", "inv": 18, "weekQty": null, "d7": null, "days": null, "status": "充足", "suggest": 0, "priority": "-"}, {"sku": "XFKF-MA-1772-26-KS", "cat": "床垫", "inv": 22, "weekQty": null, "d7": null, "days": null, "status": "充足", "suggest": 0, "priority": "-"}, {"sku": "XFKF-MA-1666-34-KS", "cat": "床垫", "inv": 12, "weekQty": null, "d7": null, "days": null, "status": "尚可", "suggest": 0, "priority": "-"}, {"sku": "XFKF-MA-1667-30-S", "cat": "床垫", "inv": 11, "weekQty": null, "d7": null, "days": null, "status": "尚可", "suggest": 0, "priority": "-"}, {"sku": "XFKF-MA-1667-30-D", "cat": "床垫", "inv": 19, "weekQty": null, "d7": null, "days": null, "status": "充足", "suggest": 0, "priority": "-"}, {"sku": "XFKF-MA-1772-26-Q", "cat": "床垫", "inv": 44, "weekQty": null, "d7": null, "days": null, "status": "充足", "suggest": 0, "priority": "-"}, {"sku": "XFKF-MA-1667-30-Q", "cat": "床垫", "inv": 32, "weekQty": null, "d7": null, "days": null, "status": "充足", "suggest": 0, "priority": "-"}]', '迁移自离线看板');
